FROM python:3.13-alpine

ENV PYTHONUNBUFFERED=1

RUN apk --no-cache add \
    curl \
    ca-certificates \
    && update-ca-certificates

RUN pip install --upgrade pip

ARG DAGSTER_VERSION=1.12.0
ARG DAGSTER_EXT_VERSION=0.28.1

RUN pip install \
    dagster~=${DAGSTER_VERSION} \
    dagster-postgres~=${DAGSTER_EXT_VERSION} \
    dagster-webserver~=${DAGSTER_EXT_VERSION}

COPY dagster.yaml workspace.yaml /

WORKDIR /
