{% macro npb4_17_01_tipos_de_cartera(key) %}
{{ return({
	"Cartera propia": "01",
	"Cartera propia 292 o. 263": "02",
	"Cartera en administración FFRAP": "03",
	"Cartera FOSAFFI - Venta de acciones": "04",
	"Cartera FOSAFFI permutada": "05",
	"Cartera FOSAFFI cedida": "06",
	"Cartera FOSAFFI permutada 292": "07",
	"Cartera FOSAFFI cedida 292": "08",
	"Cartera FOSAFFI patrimonial EX-INCAFE": "09",
	"Cartera FOSAFFI patrimonial EX-BANAFI": "10",
	"Cartera FOSAFFI transferida EX-BANCAPI": "11",
	"Cartera FOSAFFI transferida EX-BANCREPO": "12",
	"Cartera FOSAFFI transferida EX-MERCANTIL": "13",
	"Cartera FOSAFFI transferida Banco Hipotecario": "14",
	"Cartera FOSAFFI transferida BANAFI": "15",
	"Cartera MIPLAN": "16",
	"Cartera Nuevo Amanecer": "17",
	"Cartera FOSAFFI patrimonial EX-INCAFE 292": "18",
	"Cartera FOSAFFI patrimonial EX-BANAFI 292": "19",
	"Cartera FOSAFFI transferida EX-BANCAPI 292": "20",
	"Cartera FOSAFFI transferida EX-BANCREPO 292": "21",
	"Cartera FOSAFFI transferida EX-MERCANTIL 292": "22",
	"Cartera FOSAFFI transferida Banco Hipotecario 292": "23",
	"Cartera FOSAFFI transferida BANAFI 292": "24",
	"Cartera FOSAFFI transferida CREDISA": "25",
	"FIDEAGRO 292": "26",
	"FIDEAGRO": "27",
	"FICAFE": "28",
	"FEPADA": "29",
	"Cartera en administración BCR-BID": "30",
	"Derogado. (21)": "31",
	"Cartera fondo especial FONAVIPO": "32",
	"Cartera propia Ley Acceso al Crédito (19)": "33",
	"Otras 292": "98",
	"Otras": "99",
}.get(key, "99")) }}
{% endmacro %}
