version: 2

sources:
  - name: lana
    schema: "{{ env_var('DST_RAW_SCHEMA', 'raw') }}"
    tables:

      - name: cala_account_set_member_account_sets

      - name: cala_account_set_member_accounts

      - name: cala_account_sets

      - name: cala_accounts

      - name: cala_balance_history

      - name: core_chart_events_rollup

      - name: core_credit_facility_events_rollup

      - name: core_credit_facility_proposal_events_rollup

      - name: core_customer_events_rollup

      - name: core_deposit_account_events_rollup

      - name: core_deposit_events_rollup

      - name: core_disbursal_events_rollup

      - name: core_interest_accrual_cycle_events_rollup

      - name: core_obligation_events_rollup

      - name: core_payment_allocation_events_rollup

      - name: core_payment_events_rollup

      - name: core_pending_credit_facility_events_rollup

      - name: core_withdrawal_events_rollup

      - name: core_public_ids

      - name: core_chart_events

      - name: core_chart_node_events

  - name: bitfinex
    schema: "{{ env_var('DST_RAW_SCHEMA', 'raw') }}"
    tables:

      - name: bitfinex_order_book_dlt

      - name: bitfinex_order_book_dlt__orders

      - name: bitfinex_ticker_dlt

      - name: bitfinex_trades_dlt

  - name: sumsub
    schema: "{{ env_var('DST_RAW_SCHEMA', 'raw') }}"
    tables:

      - name: sumsub_applicants_dlt
